const keyCommands: Record<string, [string, string] | [string]> = {
  A: ['A'],
  B: ['B'],
  C: ['C'],
  D: ['D'],
  E: ['E'],
  F: ['F'],
  G: ['G'],
  H: ['H'],
  I: ['I'],
  J: ['J'],
  K: ['K'],
  L: ['L'],
  M: ['M'],
  N: ['N'],
  O: ['O'],
  P: ['P'],
  Q: ['Q'],
  R: ['R'],
  S: ['S'],
  T: ['T'],
  U: ['U'],
  V: ['V'],
  W: ['W'],
  X: ['X'],
  Y: ['Y'],
  Z: ['Z'],
  Kc1: ['!', '1'],
  Kc2: ['@', '2'],
  Kc3: ['#', '3'],
  Kc4: ['$', '4'],
  Kc5: ['%', '5'],
  Kc6: ['^', '6'],
  Kc7: ['&', '7'],
  Kc8: ['*', '8'],
  Kc9: ['(', '9'],
  Kc0: [')', '0'],
  Enter: ['Enter'],
  Escape: ['Esc'],
  Backspace: ['Bksp'],
  Tab: ['Tab'],
  Space: ['Space'],
  Minus: ['_', '-'],
  Equal: ['+', '='],
  LeftBracket: ['{', '['],
  RightBracket: ['}', ']'],
  Backslash: ['|', '\\'],
  Semicolon: [':', ';'],
  Quote: ['"', "'"],
  Grave: ['~', '`'],
  Comma: ['<', ','],
  Dot: ['>', '.'],
  Slash: ['?', '/'],
  CapsLock: ['CapsLock'],
  F1: ['F1'],
  F2: ['F2'],
  F3: ['F3'],
  F4: ['F4'],
  F5: ['F5'],
  F6: ['F6'],
  F7: ['F7'],
  F8: ['F8'],
  F9: ['F9'],
  F10: ['F10'],
  F11: ['F11'],
  F12: ['F12'],
  Application: ['Menu'],
  LCtrl: ['LCtrl'],
  LShift: ['LShift'],
  LAlt: ['LAlt'],
  LGui: ['LGui'],
  RCtrl: ['RCtrl'],
  RShift: ['RShift'],
  RAlt: ['RAlt'],
  RGui: ['RGui'],
  PrintScreen: ['Print', 'Screen'],
  ScrollLock: ['Scroll', 'Lock'],
  Pause: ['Pause'],
  Insert: ['Insert'],
  Home: ['Home'],
  PageUp: ['Page', 'Up'],
  Delete: ['Del'],
  End: ['End'],
  PageDown: ['Page', 'Down'],
  Right: ['Right'],
  Left: ['Left'],
  Down: ['Down'],
  UP: ['Up'],
  NumLock: ['Num', 'Lock'],
  KpSlash: ['/'],
  KpAsterisk: ['*'],
  KpMinus: ['-'],
  KpPlus: ['+'],
  KpEnter: ['Num', 'Enter'],
  Kp1: ['1'],
  Kp2: ['2'],
  Kp3: ['3'],
  Kp4: ['4'],
  Kp5: ['5'],
  Kp6: ['6'],
  Kp7: ['7'],
  Kp8: ['8'],
  Kp9: ['9'],
  Kp0: ['0'],
  KpDot: ['.'],
  KpEqual: ['='],
  KpComma: [','],
  MidiNoteD4: ['~'],
  MidiNoteDSharp2: ['!'],
  MidiNoteE2: ['@'],
  MidiNoteF2: ['#'],
  MidiNoteFSharp2: ['$'],
  MidiNoteG2: ['%'],
  MidiNoteGSharp2: ['^'],
  MidiNoteA2: ['&'],
  MidiNoteASharp2: ['*'],
  MidiNoteB2: ['('],
  MidiNoteC3: [')'],
  MidiNoteFSharp3: ['_'],
  MidiNoteG3: ['+'],
  MidiNoteGSharp3: ['{'],
  MidiNoteA3: ['}'],
  MidiNoteDSharp4: ['<'],
  MidiNoteE4: ['>'],
  MidiNoteC4: [':'],
  MidiNoteASharp3: ['|'],
  MidiNoteF4: ['?'],
  MidiNoteCSharp4: ['"'],
  NonusHash: ['~', '#'],
  NonusBackslash: ['|', '\\'],
  International1: ['_', '\\'],
  International2: ['\u30ab\u30bf\u30ab\u30ca', '\u3072\u3089\u304c\u306a'],
  International3: ['|', '\u00a5'],
  International4: ['\u5909\u63db'],
  International5: ['\u7121\u5909\u63db'],
  Language1: ['\ud55c\uc601', '\u304b\u306a'],
  Language2: ['\u6f22\u5b57', '\u82f1\u6570'],
  MidiOn: ['LSft', '(kc)'],
  MagicSwapControlCapsLock: ['LCtl', '(kc)'],
  JoystickButton0: ['LAlt', '(kc)'],
  Kb0: ['LGui', '(kc)'],
  SequencerOn: ['LCS', '(kc)'],
  Macro0: ['LCA', '(kc)'],
  BacklightOn: ['LSA', '(kc)'],
  Bootloader: ['Meh', '(kc)'],
  F13: ['F13'],
  F14: ['F14'],
  F15: ['F15'],
  F16: ['F16'],
  F17: ['F17'],
  F18: ['F18'],
  F19: ['F19'],
  F20: ['F20'],
  F21: ['F21'],
  F22: ['F22'],
  F23: ['F23'],
  F24: ['F24'],
  SystemPower: ['Power'],
  SystemSleep: ['Sleep'],
  SystemWake: ['Wake'],
  Execute: ['Exec'],
  Help: ['Help'],
  Select: ['Select'],
  Stop: ['Stop'],
  Again: ['Again'],
  Undo: ['Undo'],
  Cut: ['Cut'],
  Copy: ['Copy'],
  Paste: ['Paste'],
  Find: ['Find'],
  Calculator: ['Calc'],
  Mail: ['Mail'],
  MediaSelect: ['Media', 'Player'],
  MyComputer: ['My', 'PC'],
  WwwSearch: ['Browser', 'Search'],
  WwwHome: ['Browser', 'Home'],
  WwwBack: ['Browser', 'Back'],
  WwwForward: ['Browser', 'Forward'],
  WwwStop: ['Browser', 'Stop'],
  WwwRefresh: ['Browser', 'Refresh'],
  WwwFavorites: ['Browser', 'Fav.'],
  BrightnessUp: ['Bright.', 'Up'],
  BrightnessDown: ['Bright.', 'Down'],
  MediaPrevTrack: ['Media', 'Prev'],
  MediaNextTrack: ['Media', 'Next'],
  AudioMute: ['Mute'],
  AudioVolDown: ['Vol -'],
  AudioVolUp: ['Vol +'],
  KbVolumeDown: ['Vol -', 'Alt'],
  KbVolumeUp: ['Vol +', 'Alt'],
  MediaStop: ['Media', 'Stop'],
  MediaPlayPause: ['Media', 'Play'],
  MediaRewind: ['Prev', 'Track (macOS)'],
  MediaFastForward: ['Next', 'Track (macOS)'],
  MediaEject: ['Eject'],
  MouseUp: ['Mouse', 'Up'],
  MouseDown: ['Mouse', 'Down'],
  MouseLeft: ['Mouse', 'Left'],
  MouseRight: ['Mouse', 'Right'],
  MouseBtn1: ['Mouse', '1'],
  MouseBtn2: ['Mouse', '2'],
  MouseBtn3: ['Mouse', '3'],
  MouseBtn4: ['Mouse', '4'],
  MouseBtn5: ['Mouse', '5'],
  MouseWheelUp: ['Mouse', 'Wheel Up'],
  MouseWheelDown: ['Mouse', 'Wheel Down'],
  MouseWheelLeft: ['Mouse', 'Wheel Left'],
  MouseWheelRight: ['Mouse', 'Wheel Right'],
  MouseAccel0: ['Mouse', 'Accel 0'],
  MouseAccel1: ['Mouse', 'Accel 1'],
  MouseAccel2: ['Mouse', 'Accel 2'],
  LockingCapsLock: ['Locking', 'Caps'],
  LockingNumLock: ['Locking', 'Num'],
  LockingScrollLock: ['Locking', 'Scroll'],
};

export default (keyName: string): [string, string] | [string] => {
  return keyCommands[keyName] || [keyName];
};
